---
abstract: 'Client for 3Scale.com web API version 2.0'
author:
  - 'Owen Cliffe <zoot@zoot.org.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ThreeScale-Client
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  LWP: 0
  XML::Simple: 0
  YAML: 0
version: v2.0.2
